name: chattie
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_screenutil: ^5.8.4
  get: ^4.3.8
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.2.0+1
  image_cropper: ^5.0.0
  image_picker: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HiMelody
      fonts:
        - asset: assets/fonts/HiMelody-Regular.ttf
          weight: 700